# -*- coding: utf-8 -*-
"""Pandas Profiling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaTz1vWmOscRw63OFt1QdyUiS7v8wddt

Run the following commands
"""

pip install ydata-profiling

from ydata_profiling import ProfileReport

import pandas as pd
import numpy as np

"""Import the data"""

df=pd.read_csv('/content/StudentsPerformance.csv')

df

"""*  Make an object of the ProfileReport and provide
the df as input and run the following commands

"""

profile=ProfileReport(df)
profile.to_file('give_name_to_output_file.html')

"""Now go to the file ssection if you are working on google collab and refresh it . you'll se an html file. Download this file and open it and wallah here's the complete visualization of your data"""

